name: Tag
on:
  workflow_run:
    workflows: ["Build", "Tests"]
    types: [completed]

permissions:
  contents: write  # erlaubt Tags pushen

jobs:
  tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Ensure tags are available
        run: git fetch --tags --force

      - name: Wait until BOTH 'Build' and 'Tests' succeeded for this commit
        id: ready
        uses: actions/github-script@v7
        with:
          script: |
            const head_sha = context.payload.workflow_run.head_sha;
            const {owner, repo} = context.repo;
            const runs = await github.paginate(github.rest.actions.listWorkflowRunsForRepo, {
              owner, repo, per_page: 100, event: 'push', head_sha
            });
            const need = ['Build','Tests'];
            const ok = need.every(name =>
              runs.find(r => r.name === name && r.head_sha === head_sha && r.conclusion === 'success')
            );
            core.setOutput('ok', ok ? 'yes' : 'no');

      - name: Configure git identity for tagging
        if: steps.ready.outputs.ok == 'yes'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run semver tagging script
        if: steps.ready.outputs.ok == 'yes'
        run: bash scripts/semver-tag.sh